sudo: required
services:
    - docker

before_install:
  - docker build -t idealposter/docker-react -f Dockerfile.dev .

script:
  - docker run -e CI=true idealposter/docker-react npm run test

deploy:
  prodiver: elasticbeanstalk
  region:  "us-east-1"
  app: "docker"
  env: "Docker-env"
  bucket_name: "elasticbeanstalk-us-east-1-085211502868"
  bucket_path: "docker"
  on:
    branch: master
  access_key_id: $AWS_ACCESS_KEY
  secret_access_key: $AWS_SECRET_KEY